# ----------------------------------------------------------------------------
#
# Package             : logbook
# Source Repo         : https://github.com/getlogbook/logbook.git
# Travis Job Link     : https://travis-ci.com/github/santosh653/logbook
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
arch:
 - amd64
 - ppc64le
 
language: python
dist: xenial
addons:
  apt:
    sources:
      - chris-lea-redis-server
      - sourceline: 'ppa:chris-lea/zeromq'
    packages:
    - redis-server
    - libzmq3-dev
services:
- redis-server
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
#Excluding python2.7 on power
jobs:
 exclude:
  - python: '2.7'
    arch: ppc64le
    
before_install:
  - pip install coveralls
install:
- pip install -U pip
- pip install cython
- cython logbook/_speedups.pyx
env:
- DISABLE_LOGBOOK_CEXT=True
- CYBUILD=True

script:
- pip install -e .[all]
- if [[ $GEVENT == 'True' ]] ; then pip install gevent; fi
- pytest --cov=logbook -r s tests

matrix:
  exclude:
  include:
  - python: "3.6"
    env: GEVENT=True CYBUILD=True
    arch: amd64
  - python: "2.7"
    env: GEVENT=True CYBUILD=True
    arch: amd64
  
  
after_success:
  - coveralls

notifications:
  email:
    recipients:
    - vmalloc@gmail.com
  irc:
    channels:
    - chat.freenode.net#pocoo
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
deploy:
  - provider: pypi
    user: vmalloc
    password:
      secure: WFmuAbtBDIkeZArIFQRCwyO1TdvF2PaZpo75r3mFgnY+aWm75cdgjZKoNqVprF/f+v9EsX2kDdQ7ZfuhMLgP8MNziB+ty7579ZDGwh64jGoi+DIoeblAFu5xNAqjvhie540uCE8KySk9s+Pq5EpOA5w18V4zxTw+h6tnBQ0M9cQ=
    on:
      python: "3.7"
      condition: $CYBUILD = 'True'
      tags: true
      repo: getlogbook/logbook
    distributions: "sdist"
